# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-04 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields
import publication.models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=publication.models.image_upload_to)),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('foto_text', redactor.fields.RedactorField(null=True, verbose_name='\u0424\u043e\u0442\u043e-\u041e\u0442\u0447\u0435\u0442')),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '\u0424\u043e\u0442\u043e-\u041e\u0442\u0447\u0435\u0442',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e-\u041e\u0442\u0447\u0435\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', embed_video.fields.EmbedVideoField()),
                ('description', models.CharField(max_length=100, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0412\u0438\u0434\u0435\u043e',
                'verbose_name_plural': '\u0412\u0438\u0434\u0435\u043e',
            },
        ),
    ]
