# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-06 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-date'], 'verbose_name': '\u0424\u043e\u0442\u043e-\u041e\u0442\u0447\u0435\u0442', 'verbose_name_plural': '\u0424\u043e\u0442\u043e-\u041e\u0442\u0447\u0435\u0442\u044b'},
        ),
    ]
