# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-22 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20171014_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
