# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-04 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('body', redactor.fields.RedactorField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('rate', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u0414\u0430\u0442\u0430')),
                ('keys', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u041a\u043b\u044e\u0447\u0438')),
                ('published', models.BooleanField(default=True, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d')),
                ('is_opinion', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='author.Author')),
            ],
            options={
                'ordering': ['-date'],
                'db_table': 'opinion_opinion',
                'verbose_name': '\u041c\u043d\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041c\u043d\u0435\u043d\u0438\u044f',
            },
        ),
    ]
