# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-14 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0002_opinion_api_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='formatted_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
