# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-06 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('\u041a\u044b\u0440\u0433\u044b\u0437\u0441\u0442\u0430\u043d\u0434\u0430', '\u041a\u044b\u0440\u0433\u044b\u0437\u0441\u0442\u0430\u043d\u0434\u0430'), ('\u0414\u04af\u0439\u043d\u04e9\u0434\u04e9', '\u0414\u04af\u0439\u043d\u04e9\u0434\u04e9'), ('\u0418\u043d\u0444\u043e\u0433\u0440\u0430\u0444\u0438\u043a\u0430', '\u0418\u043d\u0444\u043e\u0433\u0440\u0430\u0444\u0438\u043a\u0430')], max_length=100, null=True),
        ),
    ]
