# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-14 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0003_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='type',
            field=models.CharField(choices=[('1', '\u0413\u043b\u0430\u0432\u043d\u0430\u044f 1'), ('2', '\u0413\u043b\u0430\u0432\u043d\u0430\u044f 2'), ('3', '\u0413\u043b\u0430\u0432\u043d\u0430\u044f 3'), ('4', '\u0421\u0442\u0430\u0442\u044c\u044f 1'), ('5', '\u0421\u0442\u0430\u0442\u044c\u044f 2')], max_length=100, null=True, verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('\u041a\u044b\u0440\u0433\u044b\u0437\u0441\u0442\u0430\u043d', '\u041a\u044b\u0440\u0433\u044b\u0437\u0441\u0442\u0430\u043d'), ('\u0414\u04af\u0439\u043d\u04e9', '\u0414\u04af\u0439\u043d\u04e9'), ('\u0418\u043d\u0444\u043e\u0433\u0440\u0430\u0444\u0438\u043a\u0430', '\u0418\u043d\u0444\u043e\u0433\u0440\u0430\u0444\u0438\u043a\u0430')], max_length=100, null=True),
        ),
    ]
