# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-21 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0005_remove_article_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='important',
            field=models.BooleanField(default=False, verbose_name='\u0412\u0430\u0436\u043d\u043e'),
        ),
    ]
