# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-04 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import publication.models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article_app', '0001_initial'),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('body', redactor.fields.RedactorField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('image', models.ImageField(blank=True, null=True, upload_to=publication.models.image_upload_to, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('audio', models.FileField(blank=True, null=True, upload_to=publication.models.image_upload_to)),
                ('view', models.IntegerField(default=0)),
                ('api_category', models.CharField(blank=True, max_length=100, null=True)),
                ('api_type', models.CharField(blank=True, max_length=100, null=True)),
                ('formatted_date', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('\u041a\u044b\u0440\u0433\u044b\u0437\u0441\u0442\u0430\u043d\u0434\u0430', '\u041a\u044b\u0440\u0433\u044b\u0437\u0441\u0442\u0430\u043d\u0434\u0430'), ('\u0414\u04af\u0439\u043d\u04e9\u0434\u04e9', '\u0414\u04af\u0439\u043d\u04e9\u0434\u04e9')], max_length=100, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u0414\u0430\u0442\u0430')),
                ('keys', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u041a\u043b\u044e\u0447\u0438')),
                ('published', models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='author.Author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article_app.Category')),
            ],
            options={
                'ordering': ['-date'],
                'db_table': 'news',
                'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='\u0412\u0430\u0448\u0435 \u0438\u043c\u044f')),
                ('text', models.TextField(verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.News')),
            ],
            options={
                'db_table': 'news_comment',
                'verbose_name': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439',
                'verbose_name_plural': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438',
            },
        ),
    ]
