# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-14 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_remove_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('\u041a\u044b\u0440\u0433\u044b\u0437\u0441\u0442\u0430\u043d', '\u041a\u044b\u0440\u0433\u044b\u0437\u0441\u0442\u0430\u043d'), ('\u0414\u04af\u0439\u043d\u04e9', '\u0414\u04af\u0439\u043d\u04e9')], max_length=100, null=True),
        ),
    ]
