# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-04 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('title', models.CharField(max_length=100)),
                ('text', redactor.fields.RedactorField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
        ),
    ]
